/* --- DATABASE UNIFICADA Y EXPANDIDA (V4.0) ---
 * Fuente: AACE Algorithm for Management of Adults With T2D — 2026 Update
 * (Endocrine Practice 32 (2026) 473–518), Algorithm Figs. 4, 5, 6, 7, 9, 10.
 * Vida media y mecanismo de acción: farmacología general (monografías/FDA labels).
 *
 * Campos:
 *  - mecanismo: mecanismo de acción, 1-2 frases.
 *  - vidaMediaHoras: vida media de eliminación aproximada, en HORAS (para graficar).
 *  - vidaMediaLabel: vida media en texto legible (ej. "~7 días").
 *  - reduccionA1c: reducción esperada de HbA1c con monoterapia (solo antidiabéticos/obesidad
 *    con efecto glucémico relevante; null si no aplica, ej. estatinas/antihipertensivos).
 *  - benef: { ic, erc, ascvd, stroke, masld } -> true si el fármaco tiene beneficio de
 *    desenlace PROBADO (no solo teórico) para esa comorbilidad, según AACE Fig. 9.
 *  - hipo: "bajo" | "moderado" | "alto"  -> riesgo de que el fármaco POR SÍ SOLO cause hipoglucemia.
 *  - peso: "perdida" | "neutro" | "ganancia" -> efecto sobre el peso.
 *  - costo: 1 ($) | 2 ($$) | 3 ($$$)  -> acceso/costo relativo.
 *  - egfrMin: eGFR mínimo (mL/min/1.73m²) para uso; null/0 = sin restricción relevante.
 *  - contra: array de códigos de comorbilidad/antecedente en los que está contraindicado.
 *  - titr: { l: [...etiquetas...], d: [...dosis...] }. Si todas las dosis son iguales,
 *    la UI muestra "Dosis Fija"; si no, se relabelan como "Titulación Inicial", "2ª...", etc.
 *  - efectoCurva (solo antidiabéticos/insulina): { peakReduction, baselineReduction,
 *    delayHoras } — modelo SIMPLIFICADO Y EDUCATIVO usado únicamente por el simulador
 *    EndoSimulators (sub-pestaña Glucosa) para contrastar visualmente "curva basal"
 *    vs. "curva con tratamiento actual" según el mecanismo de acción general de cada
 *    clase. NO es una predicción farmacocinética validada para el paciente individual.
 *      peakReduction: 0-1, fracción de reducción del pico posprandial (ej. 0.45 = 45% menos alto).
 *      baselineReduction: mg/dL de reducción de la glucosa basal/ayuno.
 *      delayHoras: cuánto retrasa el pico (ej. GLP-1/GIP y acarbosa, por enlentecer
 *      el vaciamiento gástrico o la absorción de carbohidratos).
 *  - efectoPA (solo antihipertensivos): { onsetHoras, picoHoras, duracionHoras,
 *    reduccionSistolica, reduccionDiastolica, tomasPorDia } — modelo SIMPLIFICADO Y
 *    EDUCATIVO análogo a efectoCurva, usado por EndoSimulators (sub-pestaña Presión
 *    Arterial) para proyectar cómo la hora de toma se relaciona con la cobertura
 *    antihipertensiva a lo largo de un día de 24 h. NO es una predicción
 *    farmacocinética validada para el paciente individual.
 *      onsetHoras: horas desde la toma hasta que el efecto empieza a notarse.
 *      picoHoras: horas desde la toma hasta el efecto máximo.
 *      duracionHoras: horas desde la toma hasta que el efecto se agota (ventana de
 *      cobertura VISIBLE para esta gráfica educativa — no es literalmente la vida
 *      media terminal, que ya vive por separado en vidaMediaHoras).
 *      reduccionSistolica/reduccionDiastolica: reducción máxima (mmHg) por toma.
 *      tomasPorDia: 1 (QD) o 2 (BID) — coincide con la frecuencia real de dosificación
 *      ya reflejada en `mant` (ej. Carvedilol "25 mg BID", Enalapril "20 mg BID").
 */
export const DB_PHARMA = [
  // ============ ANTIDIABÉTICOS ============
  { id: "MET", cat: "antidiabetic", grp: "Biguanidas", name: "Metformina", ini: "500 mg", mant: "2000 mg",
    adv: "Base de la terapia. Efectos GI; iniciar dosis baja y titular.",
    mecanismo: "Reduce la gluconeogénesis hepática y aumenta la sensibilidad periférica a la insulina; efecto incretina leve.",
    vidaMediaHoras: 5, vidaMediaLabel: "~5 h", reduccionA1c: "1.0-1.5%",
    titr: { l: ["Inicio", "Sem 2", "Sem 4"], d: [500, 1000, 2000] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 1, egfrMin: 30, contra: [],
    efectoCurva: { peakReduction: 0.10, baselineReduction: 5, delayHoras: 0 } },

  { id: "DAPA", cat: "antidiabetic", grp: "iSGLT2", name: "Dapagliflozina", ini: "10 mg", mant: "10 mg",
    adv: "Beneficio probado en IC (HFrEF/HFpEF) y ERC. 1a línea si hay IC o ERC.",
    mecanismo: "Inhibe SGLT2 en el túbulo contorneado proximal renal, bloqueando la reabsorción de glucosa filtrada (glucosuria).",
    vidaMediaHoras: 13, vidaMediaLabel: "~13 h", reduccionA1c: "0.5-0.8%",
    titr: { l: ["Inicio", "Mes 1"], d: [10, 10] },
    benef: { ic: true, erc: true, ascvd: false, stroke: false, masld: true },
    // evid (11-ago-2026): fuerza de evidencia POR comorbilidad — "fuerte" =
    // ensayo dedicado de desenlace duro citado en `adv`; "clase" = beneficio
    // de clase/indirecto sin ensayo dedicado propio. Usado por el desempate
    // del algoritmo de cobertura máxima en buildAntidiabeticPlan para
    // preferir evidencia sobre costo/acceso entre candidatos con la misma
    // cobertura de comorbilidades.
    evid: { ic: "fuerte", erc: "fuerte", masld: "clase" },
    hipo: "bajo", peso: "perdida", costo: 3, egfrMin: 25, contra: ["EMBARAZO"],
    efectoCurva: { peakReduction: 0.12, baselineReduction: 10, delayHoras: 0 } },

  { id: "EMPA", cat: "antidiabetic", grp: "iSGLT2", name: "Empagliflozina", ini: "10 mg", mant: "25 mg",
    adv: "Beneficio probado en IC, ERC y reducción de muerte CV en ASCVD establecida.",
    mecanismo: "Inhibe SGLT2 renal, reduciendo la reabsorción tubular de glucosa y favoreciendo su excreción urinaria.",
    vidaMediaHoras: 12, vidaMediaLabel: "~12 h", reduccionA1c: "0.6-0.9%",
    titr: { l: ["Inicio", "Mes 1"], d: [10, 25] },
    benef: { ic: true, erc: true, ascvd: true, stroke: false, masld: true },
    evid: { ic: "fuerte", erc: "fuerte", ascvd: "fuerte", masld: "clase" },
    hipo: "bajo", peso: "perdida", costo: 3, egfrMin: 20, contra: ["EMBARAZO"],
    efectoCurva: { peakReduction: 0.12, baselineReduction: 10, delayHoras: 0 } },

  { id: "CANA", cat: "antidiabetic", grp: "iSGLT2", name: "Canagliflozina", ini: "100 mg", mant: "300 mg",
    adv: "Beneficio renal robusto (CREDENCE) y reducción de MACE en ASCVD establecida.",
    mecanismo: "Inhibe SGLT2 renal, disminuyendo la reabsorción de glucosa filtrada; inhibición leve de SGLT1 intestinal a dosis altas.",
    vidaMediaHoras: 11, vidaMediaLabel: "~10-13 h", reduccionA1c: "0.7-1.0%",
    titr: { l: ["Inicio", "Mes 1"], d: [100, 300] },
    benef: { ic: true, erc: true, ascvd: true, stroke: false, masld: true },
    evid: { erc: "fuerte", ascvd: "fuerte", ic: "clase", masld: "clase" },
    hipo: "bajo", peso: "perdida", costo: 3, egfrMin: 30, contra: ["EMBARAZO"],
    efectoCurva: { peakReduction: 0.15, baselineReduction: 10, delayHoras: 0 } },

  { id: "SEMA", cat: "antidiabetic", grp: "GLP-1 RA", name: "Semaglutida SC", ini: "0.25 mg", mant: "1.0-2.0 mg",
    adv: "Pérdida de peso superior. Reduce MACE, stroke y progresión renal (FLOW).",
    mecanismo: "Agonista del receptor de GLP-1: potencia la secreción de insulina glucosa-dependiente, suprime el glucagón, enlentece el vaciamiento gástrico y aumenta la saciedad central.",
    vidaMediaHoras: 168, vidaMediaLabel: "~7 días", reduccionA1c: "1.5-1.8%",
    titr: { l: ["Sem 4", "Sem 8", "Sem 12", "Sem 16"], d: [0.25, 0.5, 1.0, 2.0] },
    benef: { ic: false, erc: true, ascvd: true, stroke: true, masld: true },
    evid: { erc: "fuerte", ascvd: "fuerte", stroke: "fuerte", masld: "clase" },
    hipo: "bajo", peso: "perdida", costo: 3, egfrMin: 15, contra: ["MEN2", "GLP1_GIP", "EMBARAZO"],
    efectoCurva: { peakReduction: 0.45, baselineReduction: 5, delayHoras: 1 } },

  { id: "SEMA_ORAL", cat: "antidiabetic", grp: "GLP-1 RA", name: "Semaglutida Oral", ini: "3 mg", mant: "14 mg",
    adv: "Única GLP-1 RA oral. Indicación FDA para prevención primaria de MACE (SOUL).",
    mecanismo: "Igual que la forma inyectable (agonismo del receptor GLP-1), coformulada con SNAC para permitir absorción gástrica.",
    vidaMediaHoras: 168, vidaMediaLabel: "~7 días", reduccionA1c: "1.0-1.4%",
    titr: { l: ["Mes 1", "Mes 2", "Mes 3"], d: [3, 7, 14] },
    benef: { ic: false, erc: false, ascvd: true, stroke: false, masld: false },
    evid: { ascvd: "fuerte" },
    hipo: "bajo", peso: "perdida", costo: 3, egfrMin: 15, contra: ["MEN2", "GLP1_GIP", "EMBARAZO"],
    efectoCurva: { peakReduction: 0.35, baselineReduction: 5, delayHoras: 0.75 } },

  { id: "DULA", cat: "antidiabetic", grp: "GLP-1 RA", name: "Dulaglutida", ini: "0.75 mg", mant: "4.5 mg",
    adv: "Indicación FDA prevención primaria de MACE (REWIND). Reduce stroke 24%.",
    mecanismo: "Agonista del receptor de GLP-1 fusionado a un fragmento Fc de IgG4, que prolonga su vida media; mismo efecto incretina que otros GLP-1 RA.",
    vidaMediaHoras: 120, vidaMediaLabel: "~5 días", reduccionA1c: "1.1-1.6%",
    titr: { l: ["Inicio", "Mes 1", "Mes 2"], d: [0.75, 1.5, 4.5] },
    benef: { ic: false, erc: true, ascvd: true, stroke: true, masld: false },
    evid: { ascvd: "fuerte", stroke: "fuerte", erc: "clase" },
    hipo: "bajo", peso: "perdida", costo: 3, egfrMin: 15, contra: ["MEN2", "GLP1_GIP", "EMBARAZO"],
    efectoCurva: { peakReduction: 0.40, baselineReduction: 5, delayHoras: 1 } },

  { id: "LIRA", cat: "antidiabetic", grp: "GLP-1 RA", name: "Liraglutida", ini: "0.6 mg", mant: "1.8 mg",
    adv: "Beneficio CV en prevención secundaria (LEADER). Requiere dosis diaria.",
    mecanismo: "Agonista del receptor de GLP-1 con unión reversible a albúmina que retrasa su degradación; acción incretina clásica.",
    vidaMediaHoras: 13, vidaMediaLabel: "~13 h", reduccionA1c: "1.0-1.5%",
    titr: { l: ["Sem 1", "Sem 2", "Sem 3"], d: [0.6, 1.2, 1.8] },
    benef: { ic: false, erc: false, ascvd: true, stroke: false, masld: true },
    evid: { ascvd: "fuerte", masld: "clase" },
    hipo: "bajo", peso: "perdida", costo: 3, egfrMin: 15, contra: ["MEN2", "GLP1_GIP", "EMBARAZO"],
    efectoCurva: { peakReduction: 0.35, baselineReduction: 5, delayHoras: 0.75 } },

  { id: "TIRZ", cat: "antidiabetic", grp: "GIP/GLP-1 RA", name: "Tirzepatida", ini: "2.5 mg", mant: "15 mg",
    adv: "Mayor eficacia glucémica y pérdida de peso. Beneficio en MASLD/MASH y HFpEF obesidad.",
    mecanismo: "Agonista dual de los receptores GIP y GLP-1; la coactivación GIP potencia el efecto incretina y la pérdida de peso más allá de un GLP-1 RA solo.",
    vidaMediaHoras: 120, vidaMediaLabel: "~5 días", reduccionA1c: "1.9-2.5%",
    titr: { l: ["Sem 4", "Sem 8", "Sem 12", "Sem 16", "Sem 20"], d: [2.5, 5, 7.5, 10, 15] },
    benef: { ic: true, erc: false, ascvd: true, stroke: true, masld: true },
    evid: { ic: "fuerte", masld: "fuerte", ascvd: "clase", stroke: "clase" },
    hipo: "bajo", peso: "perdida", costo: 3, egfrMin: 15, contra: ["MEN2", "GLP1_GIP", "EMBARAZO"],
    efectoCurva: { peakReduction: 0.55, baselineReduction: 8, delayHoras: 1.25 } },

  { id: "SITA", cat: "antidiabetic", grp: "iDPP-4", name: "Sitagliptina", ini: "100 mg", mant: "100 mg",
    adv: "Neutro en peso, seguro pero neutro en desenlaces CV/renales. Ajustar dosis en ERC.",
    mecanismo: "Inhibe la enzima DPP-4, prolongando la vida media de las incretinas endógenas (GLP-1/GIP) circulantes.",
    vidaMediaHoras: 12, vidaMediaLabel: "~12 h", reduccionA1c: "0.5-0.8%",
    titr: { l: ["Inicio"], d: [100] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 2, egfrMin: 0, contra: ["EMBARAZO"],
    efectoCurva: { peakReduction: 0.15, baselineReduction: 3, delayHoras: 0 } },

  { id: "LINA", cat: "antidiabetic", grp: "iDPP-4", name: "Linagliptina", ini: "5 mg", mant: "5 mg",
    adv: "No requiere ajuste renal (excreción biliar). Útil en ERC avanzada.",
    mecanismo: "Inhibe DPP-4 de forma competitiva y saturable, prolongando la actividad de GLP-1/GIP endógenos; eliminación predominantemente biliar.",
    vidaMediaHoras: 12, vidaMediaLabel: "~12 h (efectiva)", reduccionA1c: "0.5-0.7%",
    titr: { l: ["Inicio"], d: [5] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 2, egfrMin: 0, contra: ["EMBARAZO"],
    efectoCurva: { peakReduction: 0.15, baselineReduction: 3, delayHoras: 0 } },

  { id: "PIO", cat: "antidiabetic", grp: "TZD", name: "Pioglitazona", ini: "15 mg", mant: "45 mg",
    adv: "Beneficio en MASH y reducción de stroke recurrente (IRIS). Evitar en IC III/IV.",
    mecanismo: "Agonista de PPAR-γ en tejido adiposo, muscular y hepático; mejora la sensibilidad periférica a la insulina y redistribuye grasa visceral a subcutánea.",
    vidaMediaHoras: 20, vidaMediaLabel: "~16-24 h", reduccionA1c: "1.0-1.4%",
    titr: { l: ["Inicio", "Sem 4"], d: [15, 45] },
    benef: { ic: false, erc: false, ascvd: false, stroke: true, masld: true },
    evid: { stroke: "fuerte", masld: "fuerte" },
    hipo: "bajo", peso: "ganancia", costo: 1, egfrMin: 0, contra: ["IC", "EMBARAZO"],
    efectoCurva: { peakReduction: 0.10, baselineReduction: 12, delayHoras: 0 } },

  { id: "GLIM", cat: "antidiabetic", grp: "Sulfonilurea", name: "Glimepirida", ini: "1 mg", mant: "4 mg",
    adv: "Económica pero riesgo de hipoglucemia moderado-alto. Considerar solo por acceso/costo.",
    mecanismo: "Cierra los canales KATP de la célula beta pancreática, despolarizando la membrana y estimulando la secreción de insulina de forma NO glucosa-dependiente.",
    vidaMediaHoras: 7, vidaMediaLabel: "~5-9 h", reduccionA1c: "1.0-1.5%",
    titr: { l: ["Inicio", "Sem 2"], d: [1, 4] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "alto", peso: "ganancia", costo: 1, egfrMin: 30, contra: ["HIPOGLUCEMIA", "EMBARAZO"],
    efectoCurva: { peakReduction: 0.30, baselineReduction: 8, delayHoras: 0 } },

  { id: "ACARB", cat: "antidiabetic", grp: "AGI", name: "Acarbosa", ini: "25 mg", mant: "100 mg",
    adv: "Reduce glucosa posprandial. Efectos GI (flatulencia) limitan apego.",
    mecanismo: "Inhibe competitivamente las alfa-glucosidasas del borde en cepillo intestinal, retrasando la digestión y absorción de carbohidratos complejos.",
    vidaMediaHoras: 2, vidaMediaLabel: "~2 h (acción local)", reduccionA1c: "0.5-0.8%",
    titr: { l: ["Inicio", "Sem 4"], d: [25, 100] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 1, egfrMin: 0, contra: ["EMBARAZO"],
    efectoCurva: { peakReduction: 0.35, baselineReduction: 0, delayHoras: 0.5 } },

  { id: "GLAR", cat: "antidiabetic", grp: "Insulina Basal", name: "Insulina Glargina", ini: "0.1-0.2 U/kg/día", mant: "Titular c/2-5 días",
    adv: "Preferir análogo sobre NPH (menor hipoglucemia). Iniciar si A1c >10% o glucosa >300.",
    mecanismo: "Análogo de insulina de acción prolongada que precipita en el tejido subcutáneo, liberándose lentamente para un perfil basal ~24 h sin picos marcados.",
    vidaMediaHoras: 12, vidaMediaLabel: "~12 h (duración ~24 h)", reduccionA1c: "1.5-3.5%",
    titr: { l: ["Inicio", "Sem 1", "Sem 2"], d: [10, 14, 18] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "moderado", peso: "ganancia", costo: 2, egfrMin: 0, contra: [],
    efectoCurva: { peakReduction: 0.05, baselineReduction: 30, delayHoras: 0 } },

  { id: "DEGLU", cat: "antidiabetic", grp: "Insulina Basal", name: "Insulina Degludec", ini: "0.1-0.2 U/kg/día", mant: "Titular c/3-5 días",
    adv: "Menor incidencia de hipoglucemia nocturna que glargina.",
    mecanismo: "Forma multihexámeros solubles en el tejido subcutáneo que liberan monómeros de insulina de forma ultra-lenta y estable, prolongando su duración de acción.",
    vidaMediaHoras: 25, vidaMediaLabel: "~25 h (ultra-larga)", reduccionA1c: "1.5-3.5%",
    titr: { l: ["Inicio", "Sem 1", "Sem 2"], d: [10, 14, 18] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "ganancia", costo: 3, egfrMin: 0, contra: [],
    efectoCurva: { peakReduction: 0.05, baselineReduction: 30, delayHoras: 0 } },

  // ---- Ampliación por subgrupo (Compendio de Fármacos por Grupos Terapéuticos,
  // verificado ADA/AACE/AHA 2026) — 1-3 fármacos nuevos por cada subgrupo que
  // el motor aún no cubría, sin duplicar los que ya existían arriba. ----
  { id: "GLIB", cat: "antidiabetic", grp: "Sulfonilurea", name: "Glibenclamida", ini: "2.5 mg", mant: "10 mg",
    adv: "Sulfonilurea de mayor riesgo de hipoglucemia de la clase (vida media más larga). Evitar en adultos mayores o ERC.",
    mecanismo: "Cierra los canales KATP de la célula beta pancreática, estimulando la secreción de insulina de forma NO glucosa-dependiente; sus metabolitos activos prolongan el riesgo de hipoglucemia.",
    vidaMediaHoras: 10, vidaMediaLabel: "~10 h (metabolitos activos prolongan el efecto)", reduccionA1c: "1.0-1.5%",
    titr: { l: ["Inicio", "Sem 2"], d: [2.5, 10] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "alto", peso: "ganancia", costo: 1, egfrMin: 30, contra: ["HIPOGLUCEMIA", "EMBARAZO"],
    efectoCurva: { peakReduction: 0.30, baselineReduction: 8, delayHoras: 0 } },

  { id: "GLICLA", cat: "antidiabetic", grp: "Sulfonilurea", name: "Gliclazida", ini: "30 mg", mant: "120 mg",
    adv: "Menor riesgo de hipoglucemia que glibenclamida dentro de la clase. Liberación prolongada permite toma única diaria.",
    mecanismo: "Cierre de canales KATP igual que el resto de la clase, con mayor selectividad por el receptor SUR1 pancreático, lo que reduce el riesgo de hipoglucemia frente a glibenclamida.",
    vidaMediaHoras: 10, vidaMediaLabel: "~10-12 h", reduccionA1c: "1.0-1.5%",
    titr: { l: ["Inicio", "Sem 4"], d: [30, 120] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "moderado", peso: "ganancia", costo: 1, egfrMin: 30, contra: ["HIPOGLUCEMIA", "EMBARAZO"],
    efectoCurva: { peakReduction: 0.30, baselineReduction: 8, delayHoras: 0 } },

  { id: "REPA", cat: "antidiabetic", grp: "Meglitinida", name: "Repaglinida", ini: "0.5 mg por comida", mant: "4 mg por comida",
    adv: "Acción rápida y corta preprandial; alternativa a sulfonilurea en horarios de comida irregulares o ERC (metabolismo hepático).",
    mecanismo: "Cierra los canales KATP de la célula beta, con unión e inicio/fin de acción mucho más rápidos que las sulfonilureas, limitando su efecto al periodo posprandial.",
    vidaMediaHoras: 1, vidaMediaLabel: "~1 h", reduccionA1c: "0.5-1.0%",
    titr: { l: ["Inicio", "Sem 2"], d: [0.5, 4] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "moderado", peso: "ganancia", costo: 1, egfrMin: 0, contra: ["EMBARAZO"],
    efectoCurva: { peakReduction: 0.30, baselineReduction: 3, delayHoras: 0 } },

  { id: "NATE", cat: "antidiabetic", grp: "Meglitinida", name: "Nateglinida", ini: "60 mg por comida", mant: "120 mg por comida",
    adv: "Efecto posprandial predecible pero reducción de A1c menor que repaglinida.",
    mecanismo: "Estimula la secreción de insulina cerrando canales KATP, con inicio de acción muy rápido (minutos) y vida media corta.",
    vidaMediaHoras: 1.5, vidaMediaLabel: "~1.5 h", reduccionA1c: "0.5-0.8%",
    titr: { l: ["Inicio", "Sem 2"], d: [60, 120] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "moderado", peso: "ganancia", costo: 1, egfrMin: 0, contra: ["EMBARAZO"],
    efectoCurva: { peakReduction: 0.25, baselineReduction: 2, delayHoras: 0 } },

  { id: "ROSI", cat: "antidiabetic", grp: "TZD", name: "Rosiglitazona", ini: "4 mg", mant: "8 mg",
    adv: "Uso reservado por señal histórica de riesgo isquémico coronario (meta-análisis Nissen 2007); pioglitazona es preferida dentro de la clase. Evitar en IC.",
    mecanismo: "Agonista de PPAR-γ, mismo mecanismo que pioglitazona (mejora la sensibilidad periférica a la insulina), con perfil lipídico menos favorable.",
    vidaMediaHoras: 4, vidaMediaLabel: "~3-4 h", reduccionA1c: "1.0-1.4%",
    titr: { l: ["Inicio", "Sem 4"], d: [4, 8] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "ganancia", costo: 1, egfrMin: 0, contra: ["IC", "EMBARAZO"],
    efectoCurva: { peakReduction: 0.10, baselineReduction: 12, delayHoras: 0 } },

  { id: "ALOG", cat: "antidiabetic", grp: "iDPP-4", name: "Alogliptina", ini: "25 mg", mant: "25 mg",
    adv: "Perfil de seguridad CV neutro (EXAMINE). Ajustar dosis en ERC.",
    mecanismo: "Inhibe DPP-4, prolongando la actividad de las incretinas endógenas GLP-1/GIP.",
    vidaMediaHoras: 21, vidaMediaLabel: "~21 h", reduccionA1c: "0.5-0.8%",
    titr: { l: ["Inicio"], d: [25] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 2, egfrMin: 0, contra: ["EMBARAZO"],
    efectoCurva: { peakReduction: 0.15, baselineReduction: 3, delayHoras: 0 } },

  { id: "SAXA", cat: "antidiabetic", grp: "iDPP-4", name: "Saxagliptina", ini: "5 mg", mant: "5 mg",
    adv: "SAVOR-TIMI 53 mostró más hospitalizaciones por IC — evitar si hay IC o alto riesgo de IC.",
    mecanismo: "Inhibe DPP-4 de forma selectiva y reversible, prolongando la actividad de GLP-1/GIP endógenos.",
    vidaMediaHoras: 3, vidaMediaLabel: "~2-4 h (metabolito activo prolonga el efecto)", reduccionA1c: "0.5-0.8%",
    titr: { l: ["Inicio"], d: [5] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 2, egfrMin: 0, contra: ["IC", "EMBARAZO"],
    efectoCurva: { peakReduction: 0.15, baselineReduction: 3, delayHoras: 0 } },

  { id: "ERTU", cat: "antidiabetic", grp: "iSGLT2", name: "Ertugliflozina", ini: "5 mg", mant: "15 mg",
    adv: "Menos evidencia de desenlaces duros (VERTIS-CV neutro para MACE) frente a otros iSGLT2 — preferir dapa/empa/cana si hay IC/ERC/ASCVD.",
    mecanismo: "Inhibe SGLT2 renal, reduciendo la reabsorción tubular de glucosa filtrada.",
    vidaMediaHoras: 17, vidaMediaLabel: "~17 h", reduccionA1c: "0.6-0.9%",
    titr: { l: ["Inicio", "Mes 1"], d: [5, 15] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "perdida", costo: 3, egfrMin: 30, contra: ["EMBARAZO"],
    efectoCurva: { peakReduction: 0.12, baselineReduction: 10, delayHoras: 0 } },

  { id: "MIGL", cat: "antidiabetic", grp: "AGI", name: "Miglitol", ini: "25 mg", mant: "100 mg",
    adv: "Alternativa a acarbosa con perfil de efectos GI similar; se absorbe sistémicamente (acarbosa no).",
    mecanismo: "Inhibe las alfa-glucosidasas intestinales, retrasando la digestión de carbohidratos complejos y aplanando el pico posprandial.",
    vidaMediaHoras: 2, vidaMediaLabel: "~2 h", reduccionA1c: "0.5-0.8%",
    titr: { l: ["Inicio", "Sem 4"], d: [25, 100] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 1, egfrMin: 0, contra: ["EMBARAZO"],
    efectoCurva: { peakReduction: 0.35, baselineReduction: 0, delayHoras: 0.5 } },

  { id: "DETE", cat: "antidiabetic", grp: "Insulina Basal", name: "Insulina Detemir", ini: "0.1-0.2 U/kg/día", mant: "Titular c/3-5 días",
    adv: "Menor ganancia de peso que NPH/glargina en algunos estudios; puede requerir 2 dosis/día en algunos pacientes.",
    mecanismo: "Análogo de insulina unido a albúmina vía cadena de ácido graso, lo que retrasa su absorción y prolonga su acción de forma más plana que la NPH.",
    vidaMediaHoras: 6, vidaMediaLabel: "~5-7 h (duración ~12-20 h)", reduccionA1c: "1.5-3.5%",
    titr: { l: ["Inicio", "Sem 1", "Sem 2"], d: [10, 14, 18] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "moderado", peso: "ganancia", costo: 2, egfrMin: 0, contra: [],
    efectoCurva: { peakReduction: 0.05, baselineReduction: 28, delayHoras: 0 } },

  { id: "NPH", cat: "antidiabetic", grp: "Insulina Basal", name: "Insulina NPH", ini: "0.1-0.2 U/kg/día", mant: "Titular según glucemia",
    adv: "Opción de menor costo cuando el acceso a análogos es limitado; mayor riesgo de hipoglucemia nocturna por su pico marcado (~4-8h).",
    mecanismo: "Insulina humana en suspensión con protamina que retrasa su absorción subcutánea, generando un perfil con pico marcado (a diferencia del perfil plano de los análogos).",
    vidaMediaHoras: 6, vidaMediaLabel: "~6 h (duración 12-18 h, con pico)", reduccionA1c: "1.5-3.5%",
    titr: { l: ["Inicio", "Sem 1", "Sem 2"], d: [10, 14, 18] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "alto", peso: "ganancia", costo: 1, egfrMin: 0, contra: [],
    efectoCurva: { peakReduction: 0.05, baselineReduction: 28, delayHoras: 0 } },

  { id: "LISPRO", cat: "antidiabetic", grp: "Insulina Prandial", name: "Insulina Lispro", ini: "0.05-0.1 U/kg/comida", mant: "Ajustar según glucemia posprandial",
    adv: "Análogo de acción rápida; aplicar 0-15 min antes de la comida.",
    mecanismo: "Análogo de insulina con inversión de dos aminoácidos que acelera su disociación en hexámeros, permitiendo absorción e inicio de acción más rápidos que la insulina regular.",
    vidaMediaHoras: 1, vidaMediaLabel: "~1 h (duración 3-5 h)", reduccionA1c: "N/A (ajuste posprandial)",
    titr: { l: ["Inicio"], d: [4] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "alto", peso: "ganancia", costo: 2, egfrMin: 0, contra: [],
    efectoCurva: { peakReduction: 0.40, baselineReduction: 0, delayHoras: 0 } },

  { id: "ASPART", cat: "antidiabetic", grp: "Insulina Prandial", name: "Insulina Aspart", ini: "0.05-0.1 U/kg/comida", mant: "Ajustar según glucemia posprandial",
    adv: "Análogo de acción rápida, perfil equivalente a lispro; aplicar 0-15 min antes de la comida.",
    mecanismo: "Análogo de insulina con sustitución de un aminoácido que reduce la auto-asociación en hexámeros, acelerando la absorción subcutánea frente a la insulina regular.",
    vidaMediaHoras: 1, vidaMediaLabel: "~1 h (duración 3-5 h)", reduccionA1c: "N/A (ajuste posprandial)",
    titr: { l: ["Inicio"], d: [4] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "alto", peso: "ganancia", costo: 2, egfrMin: 0, contra: [],
    efectoCurva: { peakReduction: 0.40, baselineReduction: 0, delayHoras: 0 } },

  { id: "REGULAR", cat: "antidiabetic", grp: "Insulina Prandial", name: "Insulina Regular (Humana)", ini: "0.05-0.1 U/kg/comida", mant: "Ajustar según glucemia posprandial",
    adv: "Opción de menor costo; requiere aplicarse 30-60 min antes de la comida (inicio más lento que los análogos).",
    mecanismo: "Insulina humana no modificada; se autoasocia en hexámeros en el tejido subcutáneo, lo que retrasa su absorción frente a los análogos de acción rápida.",
    vidaMediaHoras: 1.5, vidaMediaLabel: "~1.5 h (duración 5-8 h)", reduccionA1c: "N/A (ajuste posprandial)",
    titr: { l: ["Inicio"], d: [4] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "alto", peso: "ganancia", costo: 1, egfrMin: 0, contra: [],
    efectoCurva: { peakReduction: 0.35, baselineReduction: 0, delayHoras: 0.25 } },

  // ============ OBESIDAD ============
  { id: "SEMA24", cat: "obesity", grp: "GLP-1 RA", name: "Semaglutida 2.4 mg", ini: "0.25 mg", mant: "2.4 mg",
    adv: "12-15% pérdida de peso. FDA: IMC≥30 o ≥27 con comorbilidad, ASCVD, MASH.",
    mecanismo: "Agonista del receptor de GLP-1 a nivel hipotalámico: reduce el apetito, aumenta la saciedad y enlentece el vaciamiento gástrico.",
    vidaMediaHoras: 168, vidaMediaLabel: "~7 días", reduccionA1c: "1.0-1.4%",
    titr: { l: ["Sem 4", "Sem 8", "Sem 12", "Sem 16", "Sem 20"], d: [0.25, 0.5, 1.0, 1.7, 2.4] },
    benef: { ic: false, erc: false, ascvd: true, stroke: false, masld: true },
    hipo: "bajo", peso: "perdida", costo: 3, egfrMin: 15, contra: ["MEN2", "GLP1_GIP", "EMBARAZO"] },

  { id: "TIRZ_OB", cat: "obesity", grp: "GIP/GLP-1 RA", name: "Tirzepatida (Obesidad)", ini: "2.5 mg", mant: "15 mg",
    adv: "13-20% pérdida de peso, la mayor eficacia disponible. Aprobado para OSA moderada-severa.",
    mecanismo: "Coagonismo de receptores GIP y GLP-1 que potencia la saciedad, retrasa el vaciamiento gástrico y mejora la partición energética.",
    vidaMediaHoras: 120, vidaMediaLabel: "~5 días", reduccionA1c: "N/A (uso primario: peso)",
    titr: { l: ["Sem 4", "Sem 8", "Sem 12", "Sem 16", "Sem 20"], d: [2.5, 5, 7.5, 10, 15] },
    benef: { ic: true, erc: false, ascvd: false, stroke: false, masld: true },
    hipo: "bajo", peso: "perdida", costo: 3, egfrMin: 15, contra: ["MEN2", "GLP1_GIP", "EMBARAZO"] },

  { id: "LIRA3", cat: "obesity", grp: "GLP-1 RA", name: "Liraglutida 3 mg", ini: "0.6 mg", mant: "3 mg",
    adv: "5-6% pérdida de peso. Requiere inyección diaria (menor apego vs. semanales).",
    mecanismo: "Agonismo del receptor GLP-1 central, reduciendo señales de hambre y aumentando saciedad; requiere administración diaria por su vida media corta.",
    vidaMediaHoras: 13, vidaMediaLabel: "~13 h", reduccionA1c: "N/A (uso primario: peso)",
    titr: { l: ["Sem 1", "Sem 2", "Sem 3", "Sem 4", "Sem 5"], d: [0.6, 1.2, 1.8, 2.4, 3.0] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "perdida", costo: 3, egfrMin: 15, contra: ["MEN2", "GLP1_GIP", "EMBARAZO"] },

  { id: "PHEN_TOP", cat: "obesity", grp: "Simpaticomimético/GABAérgico", name: "Fentermina/Topiramato ER", ini: "3.75/23 mg", mant: "15/92 mg",
    adv: "8-10% pérdida de peso. Alternativa oral de menor costo. Contraindicado en embarazo/glaucoma/enfermedad cardiovascular/HTA no controlada (componente fentermina, simpaticomimético).",
    mecanismo: "Fentermina libera noradrenalina hipotalámica (supresión de apetito); topiramato modula canales GABA/glutamato aumentando saciedad y termogénesis.",
    vidaMediaHoras: 20, vidaMediaLabel: "~20 h (combinado)", reduccionA1c: "N/A (uso primario: peso)",
    titr: { l: ["Sem 1", "Sem 2", "Sem 12"], d: [3.75, 7.5, 15] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    // CORRECCIÓN (misma ronda de auditoría — la ficha YA advertía en texto
    // libre "contraindicado en ASCVD/HTA no controlada" pero `contra` estaba
    // vacío, así que `filterSafe`/`currentDrugIssue` nunca aplicaban esa
    // contraindicación de verdad; el motor podía elegir este fármaco por
    // costo sin revisar riesgo cardiovascular).
    hipo: "bajo", peso: "perdida", costo: 2, egfrMin: 0, contra: ["ESTIMULANTE_CV", "EMBARAZO"] },

  { id: "NALTREX_BUP", cat: "obesity", grp: "Antagonista Opioide/NDRI", name: "Naltrexona/Bupropion ER", ini: "8/90 mg", mant: "16/180 mg BID",
    adv: "4-5% pérdida de peso. Opción si GLP-1/GIP no toleradas o no accesibles. Contraindicado en HTA no controlada (bupropion — riesgo de elevación de PA/FC).",
    mecanismo: "Naltrexona bloquea receptores opioides mu (reduce el componente hedónico/recompensa de comer); bupropion inhibe la recaptura de dopamina/noradrenalina en el hipotálamo (saciedad).",
    vidaMediaHoras: 21, vidaMediaLabel: "~21 h (bupropion)", reduccionA1c: "N/A (uso primario: peso)",
    titr: { l: ["Sem 1", "Sem 2", "Sem 3", "Sem 4"], d: [8, 16, 24, 32] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "perdida", costo: 2, egfrMin: 0, contra: ["ESTIMULANTE_CV", "EMBARAZO"] },

  { id: "ORLI", cat: "obesity", grp: "Inhibidor Lipasa GI", name: "Orlistat", ini: "60 mg", mant: "120 mg TID",
    adv: "Menor eficacia (3-4%). Efectos GI (esteatorrea) limitan apego. Costo bajo.",
    mecanismo: "Inhibe irreversiblemente las lipasas gástrica y pancreática, bloqueando la hidrólisis de triglicéridos dietéticos y reduciendo su absorción ~30%.",
    vidaMediaHoras: 2, vidaMediaLabel: "~2 h (acción local, mínima absorción)", reduccionA1c: "N/A (uso primario: peso)",
    titr: { l: ["Inicio"], d: [120] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "perdida", costo: 1, egfrMin: 0, contra: ["EMBARAZO"] },

  { id: "PHEN", cat: "obesity", grp: "Simpaticomimético/GABAérgico", name: "Fentermina", ini: "15 mg", mant: "30 mg",
    adv: "Monoterapia simpaticomimética; uso aprobado solo a corto plazo (≤12 semanas) por regulación histórica de la FDA. Contraindicado en ASCVD/HTA no controlada.",
    mecanismo: "Libera noradrenalina a nivel hipotalámico, suprimiendo el apetito por estimulación simpática central.",
    vidaMediaHoras: 20, vidaMediaLabel: "~19-24 h", reduccionA1c: "N/A (uso primario: peso)",
    titr: { l: ["Inicio", "Sem 2"], d: [15, 30] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    // CORRECCIÓN (misma ronda de auditoría): la ficha ya decía en texto libre
    // "Contraindicado en ASCVD/HTA no controlada" pero `contra` estaba vacío
    // — el motor podía elegirla por ser la más barata (costo=1) en un
    // paciente con HTA en etapa 2 sin revisar esa contraindicación real.
    hipo: "bajo", peso: "perdida", costo: 1, egfrMin: 0, contra: ["ESTIMULANTE_CV", "EMBARAZO"] },

  { id: "SETME", cat: "obesity", grp: "Agonista MC4R", name: "Setmelanotida", ini: "1 mg/día", mant: "3 mg/día",
    adv: "Indicación específica: obesidad genética por deficiencia de POMC, PCSK1 o receptor de leptina (LEPR) — no es un agente de uso general.",
    mecanismo: "Agonista del receptor de melanocortina-4 (MC4R) hipotalámico, restaurando la señal de saciedad en pacientes con defectos genéticos de la vía leptina-melanocortina.",
    vidaMediaHoras: 11, vidaMediaLabel: "~11 h", reduccionA1c: "N/A (uso primario: peso)",
    titr: { l: ["Inicio", "Sem 2"], d: [1, 3] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "perdida", costo: 3, egfrMin: 0, contra: ["EMBARAZO"] },

  // ============ HIPERTENSIÓN ============
  { id: "LOSA", cat: "htn", grp: "ARA-II", name: "Losartan", ini: "50 mg", mant: "100 mg",
    adv: "1a línea si UACR>30 mg/g. Uricosúrico leve. No combinar con IECA.",
    mecanismo: "Bloquea selectivamente el receptor AT1 de angiotensina II, impidiendo la vasoconstricción y la liberación de aldosterona.",
    vidaMediaHoras: 2, vidaMediaLabel: "~2 h (metabolito activo 6-9 h)", reduccionA1c: null,
    titr: { l: ["Inicio", "Sem 4"], d: [50, 100] },
    benef: { ic: false, erc: true, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 1, egfrMin: 0, contra: ["EMBARAZO"],
    efectoPA: { onsetHoras: 1.5, picoHoras: 5, duracionHoras: 20, reduccionSistolica: 10, reduccionDiastolica: 6, tomasPorDia: 1 } },

  { id: "TELM", cat: "htn", grp: "ARA-II", name: "Telmisartan", ini: "40 mg", mant: "80 mg",
    adv: "Vida media larga (24h+), buena cobertura nocturna.",
    mecanismo: "Bloquea el receptor AT1 de angiotensina II con alta lipofilia, lo que le da su vida media prolongada y cobertura de 24 h.",
    vidaMediaHoras: 24, vidaMediaLabel: "~24 h (la más larga de su clase)", reduccionA1c: null,
    titr: { l: ["Inicio", "Sem 4"], d: [40, 80] },
    benef: { ic: false, erc: true, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 1, egfrMin: 0, contra: ["EMBARAZO"],
    efectoPA: { onsetHoras: 1, picoHoras: 4, duracionHoras: 24, reduccionSistolica: 12, reduccionDiastolica: 7, tomasPorDia: 1 } },

  { id: "ENAL", cat: "htn", grp: "IECA", name: "Enalapril", ini: "5 mg", mant: "20 mg BID",
    adv: "1a línea alternativa a ARA-II. Tos como efecto de clase (sustituir por ARA-II si aparece, no por otro IECA — reactividad cruzada de clase). Angioedema previo con CUALQUIER IECA: contraindicación absoluta a toda la clase.",
    mecanismo: "Prodroga que se convierte en enalaprilato, inhibiendo la enzima convertidora de angiotensina y reduciendo la formación de angiotensina II.",
    vidaMediaHoras: 11, vidaMediaLabel: "~11 h (enalaprilato)", reduccionA1c: null,
    titr: { l: ["Inicio", "Sem 4"], d: [5, 20] },
    // CORRECCIÓN: benef.ic estaba en false pese a que enalapril es uno de los
    // IECA con evidencia FUNDACIONAL en insuficiencia cardíaca (CONSENSUS 1987,
    // SOLVD 1991 — reducción de mortalidad en IC con FEVI reducida), al mismo
    // nivel de evidencia que lisinopril (ATLAS) y ramipril (HOPE). No hay razón
    // clínica para que solo esos dos tuvieran benef.ic=true.
    benef: { ic: true, erc: true, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 1, egfrMin: 0, contra: ["ANGIOEDEMA", "TOS_IECA", "EMBARAZO"],
    efectoPA: { onsetHoras: 1, picoHoras: 4, duracionHoras: 10, reduccionSistolica: 8, reduccionDiastolica: 5, tomasPorDia: 2 } },

  { id: "AMLO", cat: "htn", grp: "BCC Dihidropiridínico", name: "Amlodipino", ini: "5 mg", mant: "10 mg",
    adv: "1a línea si no hay albuminuria/ERC. Edema maleolar dosis-dependiente.",
    mecanismo: "Bloquea los canales de calcio tipo L en el músculo liso vascular, produciendo vasodilatación arterial periférica.",
    vidaMediaHoras: 40, vidaMediaLabel: "~30-50 h (la más larga de su clase)", reduccionA1c: null,
    titr: { l: ["Inicio", "Sem 4"], d: [5, 10] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 1, egfrMin: 0, contra: [],
    efectoPA: { onsetHoras: 6, picoHoras: 10, duracionHoras: 24, reduccionSistolica: 10, reduccionDiastolica: 6, tomasPorDia: 1 } },

  { id: "CLOR", cat: "htn", grp: "Diurético tipo Tiazida", name: "Clortalidona", ini: "12.5 mg", mant: "25 mg",
    adv: "2a línea. Más potente que HCTZ dosis-equivalente.",
    mecanismo: "Inhibe el cotransportador Na⁺-Cl⁻ en el túbulo contorneado distal, aumentando la excreción de sodio y agua.",
    vidaMediaHoras: 50, vidaMediaLabel: "~40-60 h (permite toma única diaria)", reduccionA1c: null,
    titr: { l: ["Inicio", "Sem 4"], d: [12.5, 25] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 1, egfrMin: 0, contra: ["EMBARAZO"],
    efectoPA: { onsetHoras: 2, picoHoras: 6, duracionHoras: 22, reduccionSistolica: 9, reduccionDiastolica: 4, tomasPorDia: 1 } },

  { id: "ESPI", cat: "htn", grp: "MRA Esteroidea", name: "Espironolactona", ini: "25 mg", mant: "50 mg",
    adv: "Add-on para HTA resistente (>140/90 con 3 fármacos). Monitorizar K+ y función renal.",
    mecanismo: "Antagonista competitivo del receptor mineralocorticoide (aldosterona) en el túbulo colector, reduciendo la retención de sodio y agua.",
    vidaMediaHoras: 1.5, vidaMediaLabel: "~1.5 h (metabolitos activos hasta 20 h)", reduccionA1c: null,
    titr: { l: ["Inicio", "Sem 4"], d: [25, 50] },
    benef: { ic: true, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 1, egfrMin: 30, contra: ["EMBARAZO"],
    efectoPA: { onsetHoras: 8, picoHoras: 16, duracionHoras: 24, reduccionSistolica: 6, reduccionDiastolica: 3, tomasPorDia: 1 } },

  { id: "FINE", cat: "htn", grp: "MRA No Esteroidea", name: "Finerenona", ini: "10 mg", mant: "20 mg",
    adv: "ERC+T2D con UACR≥30 mg/g y eGFR≥25: reduce progresión renal, IC y muerte CV (FIDELIO/FIGARO).",
    mecanismo: "Antagonista no esteroideo, altamente selectivo, del receptor mineralocorticoide; reduce inflamación y fibrosis renal/cardíaca inducidas por aldosterona.",
    vidaMediaHoras: 2.5, vidaMediaLabel: "~2-3 h", reduccionA1c: null,
    titr: { l: ["Inicio", "Mes 1"], d: [10, 20] },
    benef: { ic: true, erc: true, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 3, egfrMin: 25, contra: ["EMBARAZO"],
    // Finerenona: efecto antihipertensivo modesto — su beneficio principal es
    // renal/CV (FIDELIO/FIGARO), no el control tensional en sí.
    efectoPA: { onsetHoras: 2, picoHoras: 5, duracionHoras: 14, reduccionSistolica: 3, reduccionDiastolica: 2, tomasPorDia: 1 } },

  { id: "CARV", cat: "htn", grp: "Beta-bloqueante combinado α-β", name: "Carvedilol", ini: "6.25 mg BID", mant: "25 mg BID",
    adv: "Más weight-sparing que atenolol/metoprolol. Útil si coexiste IC/angina.",
    mecanismo: "Bloquea receptores beta-1, beta-2 (reduce frecuencia cardíaca y contractilidad) y alfa-1 (vasodilatación periférica adicional).",
    vidaMediaHoras: 8, vidaMediaLabel: "~7-10 h", reduccionA1c: null,
    titr: { l: ["Inicio", "Sem 2", "Sem 4"], d: [6.25, 12.5, 25] },
    benef: { ic: true, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 2, egfrMin: 0, contra: [],
    efectoPA: { onsetHoras: 1, picoHoras: 3, duracionHoras: 10, reduccionSistolica: 8, reduccionDiastolica: 5, tomasPorDia: 2 } },

  { id: "LISI", cat: "htn", grp: "IECA", name: "Lisinopril", ini: "10 mg", mant: "40 mg",
    adv: "No requiere activación hepática (a diferencia de enalapril/ramipril) — preferible si hay disfunción hepática. Evidencia de reducción de mortalidad en IC (ATLAS).",
    mecanismo: "Inhibe directamente la ECA sin necesitar biotransformación hepática, reduciendo la formación de angiotensina II.",
    vidaMediaHoras: 12, vidaMediaLabel: "~12 h", reduccionA1c: null,
    titr: { l: ["Inicio", "Sem 4"], d: [10, 40] },
    benef: { ic: true, erc: true, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 1, egfrMin: 0, contra: ["ANGIOEDEMA", "TOS_IECA", "EMBARAZO"],
    efectoPA: { onsetHoras: 1, picoHoras: 6, duracionHoras: 24, reduccionSistolica: 9, reduccionDiastolica: 5, tomasPorDia: 1 } },

  { id: "RAMI", cat: "htn", grp: "IECA", name: "Ramipril", ini: "2.5 mg", mant: "10 mg",
    adv: "Evidencia robusta de reducción de eventos CV en alto riesgo (HOPE), incluso con PA basal cercana a la meta.",
    mecanismo: "Prodroga que se convierte en ramiprilato, inhibiendo la ECA y reduciendo angiotensina II.",
    vidaMediaHoras: 14, vidaMediaLabel: "~13-17 h (ramiprilato)", reduccionA1c: null,
    titr: { l: ["Inicio", "Sem 4"], d: [2.5, 10] },
    benef: { ic: true, erc: true, ascvd: true, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 1, egfrMin: 0, contra: ["ANGIOEDEMA", "TOS_IECA", "EMBARAZO"],
    efectoPA: { onsetHoras: 1, picoHoras: 5, duracionHoras: 24, reduccionSistolica: 9, reduccionDiastolica: 5, tomasPorDia: 1 } },

  { id: "VALS", cat: "htn", grp: "ARA-II", name: "Valsartán", ini: "80 mg", mant: "320 mg",
    adv: "Evidencia en IC con fracción de eyección reducida (Val-HeFT) además del efecto antihipertensivo.",
    mecanismo: "Bloquea selectivamente el receptor AT1 de angiotensina II.",
    vidaMediaHoras: 6, vidaMediaLabel: "~6 h", reduccionA1c: null,
    titr: { l: ["Inicio", "Sem 4"], d: [80, 320] },
    benef: { ic: true, erc: true, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 1, egfrMin: 0, contra: ["EMBARAZO"],
    efectoPA: { onsetHoras: 2, picoHoras: 4, duracionHoras: 24, reduccionSistolica: 10, reduccionDiastolica: 6, tomasPorDia: 1 } },

  { id: "NIFE", cat: "htn", grp: "BCC Dihidropiridínico", name: "Nifedipino (liberación prolongada)", ini: "30 mg", mant: "90 mg",
    adv: "Evitar la presentación de liberación inmediata (riesgo de hipotensión brusca/taquicardia refleja) — usar solo la forma de liberación prolongada.",
    mecanismo: "Bloquea canales de calcio tipo L en músculo liso vascular, produciendo vasodilatación arterial.",
    vidaMediaHoras: 10, vidaMediaLabel: "~10 h (liberación prolongada, cobertura 24 h)", reduccionA1c: null,
    titr: { l: ["Inicio", "Sem 4"], d: [30, 90] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 1, egfrMin: 0, contra: [],
    efectoPA: { onsetHoras: 4, picoHoras: 8, duracionHoras: 24, reduccionSistolica: 9, reduccionDiastolica: 5, tomasPorDia: 1 } },

  { id: "FELO", cat: "htn", grp: "BCC Dihidropiridínico", name: "Felodipino", ini: "5 mg", mant: "10 mg",
    adv: "Alternativa a amlodipino, ligeramente menor duración de acción.",
    mecanismo: "Bloquea canales de calcio tipo L, con alta selectividad vascular sobre la cardíaca.",
    vidaMediaHoras: 13, vidaMediaLabel: "~11-16 h", reduccionA1c: null,
    titr: { l: ["Inicio", "Sem 4"], d: [5, 10] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 1, egfrMin: 0, contra: [],
    efectoPA: { onsetHoras: 3, picoHoras: 6, duracionHoras: 22, reduccionSistolica: 8, reduccionDiastolica: 5, tomasPorDia: 1 } },

  { id: "VERA", cat: "htn", grp: "BCC No Dihidropiridínico", name: "Verapamilo (liberación prolongada)", ini: "120 mg", mant: "240 mg",
    adv: "Útil si coexiste taquiarritmia supraventricular. Evitar combinar con betabloqueante (riesgo de bloqueo AV/bradicardia severa).",
    mecanismo: "Bloquea canales de calcio tipo L con efecto adicional cronotrópico e inotrópico negativo (acción sobre el nodo AV), a diferencia de las dihidropiridinas.",
    vidaMediaHoras: 6, vidaMediaLabel: "~4-8 h (liberación prolongada: cobertura 24 h)", reduccionA1c: null,
    titr: { l: ["Inicio", "Sem 4"], d: [120, 240] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 1, egfrMin: 0, contra: ["IC"],
    efectoPA: { onsetHoras: 2, picoHoras: 5, duracionHoras: 24, reduccionSistolica: 8, reduccionDiastolica: 5, tomasPorDia: 1 } },

  { id: "DILT", cat: "htn", grp: "BCC No Dihidropiridínico", name: "Diltiazem (liberación prolongada)", ini: "120 mg", mant: "360 mg",
    adv: "Alternativa a verapamilo, algo menos inotrópico negativo. Evitar combinar con betabloqueante.",
    mecanismo: "Bloquea canales de calcio tipo L con efecto sobre el nodo AV/SA además de la vasodilatación periférica.",
    vidaMediaHoras: 6, vidaMediaLabel: "~4-6 h (liberación prolongada: cobertura 24 h)", reduccionA1c: null,
    titr: { l: ["Inicio", "Sem 4"], d: [120, 360] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 1, egfrMin: 0, contra: ["IC"],
    efectoPA: { onsetHoras: 2, picoHoras: 5, duracionHoras: 24, reduccionSistolica: 8, reduccionDiastolica: 5, tomasPorDia: 1 } },

  { id: "HCTZ", cat: "htn", grp: "Diurético tipo Tiazida", name: "Hidroclorotiazida", ini: "12.5 mg", mant: "25 mg",
    adv: "El diurético tiazídico más usado; clortalidona tiene evidencia de mayor reducción de eventos CV a dosis equivalente.",
    mecanismo: "Inhibe el cotransportador Na⁺-Cl⁻ en el túbulo contorneado distal.",
    vidaMediaHoras: 10, vidaMediaLabel: "~6-15 h", reduccionA1c: null,
    titr: { l: ["Inicio", "Sem 4"], d: [12.5, 25] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 1, egfrMin: 0, contra: ["EMBARAZO"],
    efectoPA: { onsetHoras: 2, picoHoras: 4, duracionHoras: 12, reduccionSistolica: 8, reduccionDiastolica: 4, tomasPorDia: 1 } },

  { id: "INDA", cat: "htn", grp: "Diurético tipo Tiazida", name: "Indapamida", ini: "1.25 mg", mant: "2.5 mg",
    adv: "Evidencia de reducción de stroke (PROGRESS, HYVET) en adultos mayores.",
    mecanismo: "Similar a las tiazidas (inhibe el cotransportador Na⁺-Cl⁻), con efecto vasodilatador adicional independiente de su acción diurética.",
    vidaMediaHoras: 16, vidaMediaLabel: "~14-18 h", reduccionA1c: null,
    titr: { l: ["Inicio", "Sem 4"], d: [1.25, 2.5] },
    benef: { ic: false, erc: false, ascvd: false, stroke: true, masld: false },
    hipo: "bajo", peso: "neutro", costo: 1, egfrMin: 0, contra: ["EMBARAZO"],
    efectoPA: { onsetHoras: 2, picoHoras: 6, duracionHoras: 24, reduccionSistolica: 9, reduccionDiastolica: 4, tomasPorDia: 1 } },

  { id: "FURO", cat: "htn", grp: "Diurético de Asa", name: "Furosemida", ini: "20 mg", mant: "80 mg",
    adv: "Reservado para sobrecarga de volumen (IC, ERC avanzada) — poco eficaz como antihipertensivo puro en función renal normal por su vida media corta.",
    mecanismo: "Inhibe el cotransportador Na⁺-K⁺-2Cl⁻ en el asa ascendente de Henle, generando diuresis potente pero de acción corta.",
    vidaMediaHoras: 2, vidaMediaLabel: "~1.5-2 h", reduccionA1c: null,
    titr: { l: ["Inicio", "Sem 2"], d: [20, 80] },
    benef: { ic: true, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 1, egfrMin: 0, contra: ["EMBARAZO"],
    efectoPA: { onsetHoras: 1, picoHoras: 2, duracionHoras: 6, reduccionSistolica: 5, reduccionDiastolica: 3, tomasPorDia: 2 } },

  { id: "TORSE", cat: "htn", grp: "Diurético de Asa", name: "Torsemida", ini: "5 mg", mant: "20 mg",
    adv: "Mayor biodisponibilidad y vida media más predecible que furosemida — preferido en ERC/IC cuando la absorción de furosemida es errática.",
    mecanismo: "Inhibe el cotransportador Na⁺-K⁺-2Cl⁻ en el asa de Henle, con mayor biodisponibilidad oral y duración de acción más prolongada que furosemida.",
    vidaMediaHoras: 3.5, vidaMediaLabel: "~3-4 h", reduccionA1c: null,
    titr: { l: ["Inicio", "Sem 2"], d: [5, 20] },
    benef: { ic: true, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 2, egfrMin: 0, contra: ["EMBARAZO"],
    efectoPA: { onsetHoras: 1, picoHoras: 3, duracionHoras: 12, reduccionSistolica: 6, reduccionDiastolica: 3, tomasPorDia: 1 } },

  { id: "EPLE", cat: "htn", grp: "MRA Esteroidea", name: "Eplerenona", ini: "25 mg", mant: "50 mg",
    adv: "Menor incidencia de ginecomastia/mastodinia que espironolactona (mayor selectividad). Evidencia en IC post-IAM (EPHESUS) y HFrEF (EMPHASIS-HF).",
    mecanismo: "Antagonista selectivo del receptor mineralocorticoide, con menor afinidad cruzada por receptores androgénicos/progestágenos que espironolactona.",
    vidaMediaHoras: 5, vidaMediaLabel: "~4-6 h", reduccionA1c: null,
    titr: { l: ["Inicio", "Sem 4"], d: [25, 50] },
    benef: { ic: true, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 2, egfrMin: 30, contra: ["EMBARAZO"],
    efectoPA: { onsetHoras: 4, picoHoras: 10, duracionHoras: 24, reduccionSistolica: 6, reduccionDiastolica: 3, tomasPorDia: 1 } },

  { id: "LABE", cat: "htn", grp: "Beta-bloqueante combinado α-β", name: "Labetalol", ini: "100 mg BID", mant: "600 mg/día",
    adv: "Antihipertensivo de elección en HTA gestacional/preeclampsia (junto con metildopa).",
    mecanismo: "Bloquea receptores beta-1, beta-2 y alfa-1, combinando reducción de frecuencia cardíaca con vasodilatación periférica.",
    vidaMediaHoras: 7, vidaMediaLabel: "~6-8 h", reduccionA1c: null,
    titr: { l: ["Inicio", "Sem 2", "Sem 4"], d: [200, 400, 600] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 1, egfrMin: 0, contra: [],
    efectoPA: { onsetHoras: 1, picoHoras: 3, duracionHoras: 12, reduccionSistolica: 8, reduccionDiastolica: 5, tomasPorDia: 2 } },

  { id: "BISO", cat: "htn", grp: "Beta-bloqueante Cardioselectivo", name: "Bisoprolol", ini: "2.5 mg", mant: "10 mg",
    adv: "Evidencia de reducción de mortalidad en HFrEF (CIBIS-II). Cardioselectivo — menor efecto en receptores beta-2 (broncoespasmo) que betabloqueantes no selectivos.",
    mecanismo: "Bloquea selectivamente receptores beta-1 cardíacos, reduciendo frecuencia cardíaca y contractilidad con menor efecto sobre el músculo liso bronquial/vascular periférico.",
    vidaMediaHoras: 11, vidaMediaLabel: "~10-12 h", reduccionA1c: null,
    titr: { l: ["Inicio", "Sem 4"], d: [2.5, 10] },
    benef: { ic: true, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 1, egfrMin: 0, contra: [],
    efectoPA: { onsetHoras: 2, picoHoras: 4, duracionHoras: 24, reduccionSistolica: 7, reduccionDiastolica: 4, tomasPorDia: 1 } },

  { id: "METOS", cat: "htn", grp: "Beta-bloqueante Cardioselectivo", name: "Metoprolol Succinato", ini: "25 mg", mant: "200 mg",
    adv: "Evidencia de reducción de mortalidad en HFrEF (MERIT-HF). Preferir la forma succinato (liberación prolongada) sobre tartrato para dosis única diaria.",
    mecanismo: "Bloquea selectivamente receptores beta-1 cardíacos; la formulación succinato libera el fármaco de forma prolongada, dando cobertura de 24 h.",
    vidaMediaHoras: 7, vidaMediaLabel: "~3-7 h (liberación prolongada: cobertura 24 h)", reduccionA1c: null,
    titr: { l: ["Inicio", "Sem 4"], d: [25, 200] },
    benef: { ic: true, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 1, egfrMin: 0, contra: [],
    efectoPA: { onsetHoras: 2, picoHoras: 4, duracionHoras: 24, reduccionSistolica: 7, reduccionDiastolica: 4, tomasPorDia: 1 } },

  { id: "DOXA", cat: "htn", grp: "Alfabloqueante", name: "Doxazosina", ini: "1 mg", mant: "8 mg",
    adv: "Útil si coexiste hiperplasia prostática benigna. No es de primera línea en monoterapia (ALLHAT: más eventos de IC vs. clortalidona) — reservar para HTA resistente/add-on.",
    mecanismo: "Bloquea selectivamente receptores alfa-1 postsinápticos, produciendo vasodilatación arterial y venosa periférica.",
    vidaMediaHoras: 22, vidaMediaLabel: "~22 h", reduccionA1c: null,
    titr: { l: ["Inicio", "Sem 4"], d: [1, 8] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 1, egfrMin: 0, contra: ["IC"],
    efectoPA: { onsetHoras: 2, picoHoras: 4, duracionHoras: 24, reduccionSistolica: 7, reduccionDiastolica: 4, tomasPorDia: 1 } },

  { id: "PRAZ", cat: "htn", grp: "Alfabloqueante", name: "Prazosina", ini: "1 mg BID", mant: "20 mg/día",
    adv: "Relevancia endocrina: fármaco de elección para el bloqueo alfa preoperatorio en feocromocitoma/paraganglioma antes de cirugía.",
    mecanismo: "Bloquea receptores alfa-1 postsinápticos, con vida media corta que requiere dosificación múltiple.",
    vidaMediaHoras: 2.5, vidaMediaLabel: "~2-3 h", reduccionA1c: null,
    titr: { l: ["Inicio", "Sem 2", "Sem 4"], d: [2, 6, 20] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 1, egfrMin: 0, contra: [],
    efectoPA: { onsetHoras: 1, picoHoras: 3, duracionHoras: 8, reduccionSistolica: 6, reduccionDiastolica: 4, tomasPorDia: 2 } },

  { id: "HIDRA", cat: "htn", grp: "Vasodilatador Directo", name: "Hidralazina", ini: "10 mg QID", mant: "300 mg/día",
    adv: "Combinada con nitrato de acción prolongada: reduce mortalidad en IC con FEVI reducida en pacientes afrodescendientes (A-HeFT). Taquicardia refleja — combinar con betabloqueante.",
    mecanismo: "Vasodilatador arterial directo por relajación del músculo liso vascular, mecanismo independiente del sistema renina-angiotensina.",
    vidaMediaHoras: 5, vidaMediaLabel: "~2-8 h (variable según acetilación)", reduccionA1c: null,
    titr: { l: ["Inicio", "Sem 2", "Sem 4"], d: [40, 100, 300] },
    benef: { ic: true, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 1, egfrMin: 0, contra: [],
    efectoPA: { onsetHoras: 1, picoHoras: 2, duracionHoras: 6, reduccionSistolica: 7, reduccionDiastolica: 5, tomasPorDia: 2 } },

  { id: "MINOX", cat: "htn", grp: "Vasodilatador Directo", name: "Minoxidil", ini: "2.5 mg", mant: "40 mg",
    adv: "Reservado para HTA resistente refractaria a combinaciones estándar; causa retención de líquidos e hirsutismo — combinar siempre con diurético de asa y betabloqueante.",
    mecanismo: "Abre canales de potasio ATP-dependientes en el músculo liso vascular, produciendo vasodilatación arterial potente.",
    vidaMediaHoras: 4, vidaMediaLabel: "~4 h", reduccionA1c: null,
    titr: { l: ["Inicio", "Sem 4"], d: [2.5, 40] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 1, egfrMin: 0, contra: ["IC"],
    efectoPA: { onsetHoras: 1, picoHoras: 3, duracionHoras: 24, reduccionSistolica: 10, reduccionDiastolica: 6, tomasPorDia: 1 } },

  { id: "CLONI", cat: "htn", grp: "Agente Central", name: "Clonidina", ini: "0.1 mg BID", mant: "1.2 mg/día",
    adv: "Riesgo de hipertensión de rebote si se suspende abruptamente — retirar de forma gradual. Reservada para HTA resistente/add-on.",
    mecanismo: "Agonista alfa-2 adrenérgico central, que reduce el flujo simpático eferente desde el tronco encefálico.",
    vidaMediaHoras: 7, vidaMediaLabel: "~6-8 h", reduccionA1c: null,
    titr: { l: ["Inicio", "Sem 2", "Sem 4"], d: [0.2, 0.6, 1.2] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 1, egfrMin: 0, contra: [],
    efectoPA: { onsetHoras: 1, picoHoras: 3, duracionHoras: 8, reduccionSistolica: 7, reduccionDiastolica: 5, tomasPorDia: 2 } },

  { id: "METILD", cat: "htn", grp: "Agente Central", name: "Metildopa", ini: "250 mg BID", mant: "3 g/día",
    adv: "Relevancia endocrina: antihipertensivo de primera línea en el embarazo por su extenso perfil de seguridad establecido.",
    mecanismo: "Se convierte en alfa-metilnoradrenalina, un agonista alfa-2 central que reduce el tono simpático, mecanismo análogo a clonidina.",
    vidaMediaHoras: 2, vidaMediaLabel: "~2 h (efecto prolongado por metabolito activo)", reduccionA1c: null,
    titr: { l: ["Inicio", "Sem 2", "Sem 4"], d: [500, 1000, 3000] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 1, egfrMin: 0, contra: [],
    efectoPA: { onsetHoras: 4, picoHoras: 8, duracionHoras: 12, reduccionSistolica: 6, reduccionDiastolica: 4, tomasPorDia: 2 } },

  // ============ DISLIPIDEMIA ============
  { id: "ATOR", cat: "lipid", grp: "Estatina Alta Intensidad", name: "Atorvastatina", ini: "20 mg", mant: "40-80 mg",
    adv: "Alta intensidad (50-60% reducción LDL). 1a línea en riesgo alto/muy alto.",
    mecanismo: "Inhibe competitivamente la HMG-CoA reductasa hepática, enzima limitante de la síntesis de colesterol; aumenta receptores LDL hepáticos.",
    vidaMediaHoras: 14, vidaMediaLabel: "~14 h (metabolitos activos hasta 20-30 h)", reduccionA1c: null,
    titr: { l: ["Inicio", "4 Sem", "8 Sem"], d: [20, 40, 80] },
    benef: { ic: false, erc: false, ascvd: true, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 1, egfrMin: 0, contra: ["EMBARAZO"] },

  { id: "ROSU", cat: "lipid", grp: "Estatina Alta Intensidad", name: "Rosuvastatina", ini: "10 mg", mant: "20-40 mg",
    adv: "Máxima potencia de reducción de LDL-C entre estatinas.",
    mecanismo: "Inhibe la HMG-CoA reductasa con alta afinidad hepatoselectiva, maximizando la reducción de LDL-C con baja exposición sistémica.",
    vidaMediaHoras: 19, vidaMediaLabel: "~19 h", reduccionA1c: null,
    titr: { l: ["Inicio", "4 Sem", "8 Sem"], d: [10, 20, 40] },
    benef: { ic: false, erc: false, ascvd: true, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 1, egfrMin: 0, contra: ["EMBARAZO"] },

  { id: "PRAVA", cat: "lipid", grp: "Estatina Baja/Moderada Intensidad", name: "Pravastatina", ini: "20 mg", mant: "80 mg",
    adv: "Hidrofílica, menor riesgo de miopatía. Útil si hay intolerancia a otras estatinas.",
    mecanismo: "Inhibe la HMG-CoA reductasa; su hidrofilia limita la penetración muscular, reduciendo el riesgo de miopatía frente a estatinas lipofílicas.",
    vidaMediaHoras: 1.8, vidaMediaLabel: "~1.5-2 h", reduccionA1c: null,
    titr: { l: ["Inicio", "4 Sem"], d: [20, 80] },
    benef: { ic: false, erc: false, ascvd: true, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 1, egfrMin: 0, contra: ["EMBARAZO"] },

  { id: "EZE", cat: "lipid", grp: "Inhibidor de Absorción", name: "Ezetimibe", ini: "10 mg", mant: "10 mg",
    adv: "Add-on de 1a elección si no se alcanza meta con estatina a dosis máxima tolerada.",
    mecanismo: "Bloquea la proteína transportadora NPC1L1 en el borde en cepillo intestinal, inhibiendo la absorción de colesterol dietético y biliar.",
    vidaMediaHoras: 22, vidaMediaLabel: "~22 h (glucurónido activo)", reduccionA1c: null,
    titr: { l: ["Inicio"], d: [10] },
    benef: { ic: false, erc: false, ascvd: true, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 1, egfrMin: 0, contra: ["EMBARAZO"] },

  { id: "BEMP", cat: "lipid", grp: "Inhibidor ATP-Citrato Liasa", name: "Ácido Bempedoico", ini: "180 mg", mant: "180 mg",
    adv: "Add-on si meta no alcanzada con estatina+ezetimibe. Precaución: gota, riesgo de rotura tendinosa.",
    mecanismo: "Inhibe la ATP-citrato liasa, un paso previo a la HMG-CoA reductasa en la síntesis de colesterol; se activa selectivamente en hígado (evita miopatía).",
    vidaMediaHoras: 21, vidaMediaLabel: "~21 h", reduccionA1c: null,
    titr: { l: ["Inicio"], d: [180] },
    benef: { ic: false, erc: false, ascvd: true, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 3, egfrMin: 0, contra: ["EMBARAZO"] },

  { id: "EVOLO", cat: "lipid", grp: "PCSK9i (mAb)", name: "Evolocumab", ini: "140 mg c/2sem", mant: "140 mg c/2sem",
    adv: "Reduce MACE. Indicado en alto riesgo ASCVD con LDL sobre meta pese a terapia máxima.",
    mecanismo: "Anticuerpo monoclonal que inhibe PCSK9, impidiendo la degradación del receptor de LDL hepático y aumentando su reciclaje/densidad en superficie.",
    vidaMediaHoras: 312, vidaMediaLabel: "~11-17 días", reduccionA1c: null,
    titr: { l: ["Inicio"], d: [140] },
    benef: { ic: false, erc: false, ascvd: true, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 3, egfrMin: 0, contra: ["EMBARAZO"] },

  { id: "ALIRO", cat: "lipid", grp: "PCSK9i (mAb)", name: "Alirocumab", ini: "75 mg c/2sem", mant: "150 mg c/2sem",
    adv: "Aprobado para ASCVD ya establecida (prevención secundaria).",
    mecanismo: "Anticuerpo monoclonal anti-PCSK9; mismo mecanismo que evolocumab, aumentando la disponibilidad de receptores LDL hepáticos.",
    vidaMediaHoras: 432, vidaMediaLabel: "~17-20 días", reduccionA1c: null,
    titr: { l: ["Inicio", "Sem 4"], d: [75, 150] },
    benef: { ic: false, erc: false, ascvd: true, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 3, egfrMin: 0, contra: ["EMBARAZO"] },

  { id: "IPE", cat: "lipid", grp: "Ácido Icosapentaenoico", name: "Icosapent Etilo", ini: "2 g BID", mant: "2 g BID",
    adv: "TG 150-499 con ASCVD o ≥2 factores de riesgo en estatina a dosis máxima: reduce CVD 25% (REDUCE-IT).",
    mecanismo: "Éster etílico de EPA purificado que se incorpora a membranas celulares y lipoproteínas, reduciendo triglicéridos y ejerciendo efectos antiinflamatorios/antitrombóticos pleiotrópicos.",
    vidaMediaHoras: 89, vidaMediaLabel: "~89 h", reduccionA1c: null,
    titr: { l: ["Inicio"], d: [4] },
    benef: { ic: false, erc: false, ascvd: true, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 3, egfrMin: 0, contra: ["EMBARAZO"] },

  { id: "FENO", cat: "lipid", grp: "Fibrato", name: "Fenofibrato", ini: "145 mg", mant: "145 mg",
    adv: "Reservado para TG≥500 mg/dL (prevención de pancreatitis), no para reducir ASCVD.",
    mecanismo: "Agonista de PPAR-α que induce la lipoproteín-lipasa y reduce la síntesis de apoC-III, acelerando el catabolismo de partículas ricas en triglicéridos.",
    vidaMediaHoras: 20, vidaMediaLabel: "~20 h", reduccionA1c: null,
    titr: { l: ["Inicio"], d: [145] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 1, egfrMin: 30, contra: ["EMBARAZO"] },

  { id: "SIMVA", cat: "lipid", grp: "Estatina Baja/Moderada Intensidad", name: "Simvastatina", ini: "20 mg", mant: "40 mg",
    adv: "Interacción relevante con amlodipino/verapamilo/diltiazem (limitar a 20 mg/día en combinación) por riesgo de miopatía. Dosis de 80 mg ya no se recomienda (FDA, riesgo de rabdomiólisis).",
    mecanismo: "Inhibe la HMG-CoA reductasa hepática, reduciendo la síntesis de colesterol y aumentando la expresión de receptores LDL.",
    vidaMediaHoras: 3, vidaMediaLabel: "~2-3 h", reduccionA1c: null,
    titr: { l: ["Inicio", "4 Sem"], d: [20, 40] },
    benef: { ic: false, erc: false, ascvd: true, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 1, egfrMin: 0, contra: ["EMBARAZO"] },

  { id: "PITA", cat: "lipid", grp: "Estatina Baja/Moderada Intensidad", name: "Pitavastatina", ini: "2 mg", mant: "4 mg",
    adv: "Mínima interacción con CYP3A4 — útil en pacientes polimedicados. Perfil neutro sobre glucemia (relevante en T2D).",
    mecanismo: "Inhibe la HMG-CoA reductasa; metabolismo mínimo por CYP450, lo que reduce el riesgo de interacciones farmacológicas frente a otras estatinas.",
    vidaMediaHoras: 5, vidaMediaLabel: "~5 h", reduccionA1c: null,
    titr: { l: ["Inicio", "4 Sem"], d: [2, 4] },
    benef: { ic: false, erc: false, ascvd: true, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 2, egfrMin: 0, contra: ["EMBARAZO"] },

  { id: "INCLI", cat: "lipid", grp: "PCSK9i (siRNA)", name: "Inclisirán", ini: "284 mg SC", mant: "284 mg SC c/6 meses",
    adv: "Administración cada 6 meses (tras dosis de refuerzo a los 3 meses) — máxima adherencia posible dentro de la clase PCSK9i. Mismo escalón que evolocumab/alirocumab.",
    mecanismo: "ARN de interferencia pequeño (siRNA) que silencia la síntesis hepática de PCSK9, aumentando la disponibilidad de receptores LDL de forma sostenida.",
    vidaMediaHoras: 0, vidaMediaLabel: "Efecto sostenido ~6 meses (no aplica vida media plasmática convencional)", reduccionA1c: null,
    titr: { l: ["Inicio", "Mes 3", "Mes 9"], d: [284, 284, 284] },
    benef: { ic: false, erc: false, ascvd: true, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 3, egfrMin: 0, contra: ["EMBARAZO"] },

  { id: "GEMFI", cat: "lipid", grp: "Fibrato", name: "Gemfibrozilo", ini: "600 mg BID", mant: "1200 mg/día",
    adv: "NO combinar con estatinas (inhibe su glucuronidación, riesgo alto de rabdomiólisis) — si se requiere fibrato + estatina, usar fenofibrato.",
    mecanismo: "Agonista de PPAR-α que reduce la síntesis hepática de triglicéridos y aumenta el catabolismo de lipoproteínas ricas en triglicéridos.",
    vidaMediaHoras: 1.5, vidaMediaLabel: "~1-2 h", reduccionA1c: null,
    titr: { l: ["Inicio"], d: [1200] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 1, egfrMin: 30, contra: ["EMBARAZO"] },

  { id: "COLESEV", cat: "lipid", grp: "Secuestrante de Ácidos Biliares", name: "Colesevelam", ini: "1.875 g/día", mant: "4.375 g/día",
    adv: "Mejor tolerabilidad GI que colestiramina/colestipol. Beneficio adicional: reduce HbA1c ~0.5% — opción útil si coexiste dislipidemia + T2D con estatina no tolerada.",
    mecanismo: "Se une a ácidos biliares en el intestino, interrumpiendo su recirculación enterohepática y forzando al hígado a usar colesterol para sintetizar más ácidos biliares.",
    vidaMediaHoras: 0, vidaMediaLabel: "No se absorbe sistémicamente (acción local intestinal)", reduccionA1c: "0.3-0.5% (efecto adicional, no es su indicación primaria)",
    titr: { l: ["Inicio", "Sem 4"], d: [1.875, 4.375] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 2, egfrMin: 0, contra: ["EMBARAZO"] },

  // ============ OTROS / INTERACCIONES RELEVANTES ============
  // Categoría nueva (10-ago-2026, a petición del Dr. Ortega): antes AINE/
  // Litio/Antipsicótico-alto-riesgo/TARV-potenciado vivían como banderas sí/no
  // en el formulario ("¿usa AINE?"), sin fármaco específico — el médico no
  // tenía dónde registrar CUÁL, y el expediente/PDF tampoco lo mostraba. Se
  // migran aquí como fármacos concretos dentro de Medicación Actual, mismo
  // patrón (checkbox + dosis máxima + dosis/frecuencia) que antidiabetic/htn/
  // lipid/obesity. NO se agregan a EndoFarma (catálogo de consulta libre,
  // CATEGORIA_ORDER en render.js) — el alcance de este cambio es solo
  // Medicación Actual + los checks de interacción de las Capas 1-4/Dominios
  // 1/3/5 (polypharmacy.js/psychiatry.js/hiv-art.js), no el catálogo de
  // prescripción nueva (ninguno de estos fármacos se RECOMIENDA desde el
  // motor, solo se detecta si ya están en uso). `benef` va todo en false y
  // `hipo`/`peso` quedan neutros porque no participan del algoritmo de
  // selección/ranking — solo currentDrugIssue/checks dedicados los leen.
  { id: "IBU", cat: "otros", grp: "AINE", name: "Ibuprofeno", ini: "N/A", mant: "N/A",
    adv: "AINE no selectivo de uso libre/frecuente. Riesgo renal/GI de clase — ver Casos 45 y 47 (Tríada Mortal / nefrotoxicidad en ERC).",
    mecanismo: "Inhibe COX-1/COX-2, reduciendo síntesis de prostaglandinas — incluidas las que mantienen la perfusión de la arteriola aferente renal.",
    vidaMediaHoras: 2, vidaMediaLabel: "~2 h", reduccionA1c: null,
    titr: { l: ["Uso actual"], d: [1] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 1, egfrMin: 0, contra: ["EMBARAZO"] },

  { id: "NAPRO", cat: "otros", grp: "AINE", name: "Naproxeno", ini: "N/A", mant: "N/A",
    adv: "AINE no selectivo de vida media más larga (BID) — mismo riesgo renal/GI de clase.",
    mecanismo: "Inhibe COX-1/COX-2, reduciendo síntesis de prostaglandinas — incluidas las que mantienen la perfusión de la arteriola aferente renal.",
    vidaMediaHoras: 14, vidaMediaLabel: "~12-17 h", reduccionA1c: null,
    titr: { l: ["Uso actual"], d: [1] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 1, egfrMin: 0, contra: ["EMBARAZO"] },

  { id: "DICLO", cat: "otros", grp: "AINE", name: "Diclofenaco", ini: "N/A", mant: "N/A",
    adv: "AINE no selectivo, disponible oral/tópico/parenteral — mismo riesgo renal/GI de clase.",
    mecanismo: "Inhibe COX-1/COX-2, reduciendo síntesis de prostaglandinas — incluidas las que mantienen la perfusión de la arteriola aferente renal.",
    vidaMediaHoras: 1.5, vidaMediaLabel: "~1-2 h", reduccionA1c: null,
    titr: { l: ["Uso actual"], d: [1] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 1, egfrMin: 0, contra: ["EMBARAZO"] },

  { id: "KETOR", cat: "otros", grp: "AINE", name: "Ketorolaco", ini: "N/A", mant: "N/A",
    adv: "AINE de mayor potencia analgésica, uso típicamente corto (≤5 días) — mismo riesgo renal/GI de clase, más marcado por su potencia.",
    mecanismo: "Inhibe COX-1/COX-2, reduciendo síntesis de prostaglandinas — incluidas las que mantienen la perfusión de la arteriola aferente renal.",
    vidaMediaHoras: 5, vidaMediaLabel: "~5 h", reduccionA1c: null,
    titr: { l: ["Uso actual"], d: [1] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 1, egfrMin: 0, contra: ["EMBARAZO"] },

  { id: "CELEC", cat: "otros", grp: "AINE", name: "Celecoxib", ini: "N/A", mant: "N/A",
    adv: "AINE COX-2 selectivo — menor riesgo GI que los no selectivos, pero el riesgo RENAL de clase (arteriola aferente) se mantiene igual.",
    mecanismo: "Inhibe selectivamente COX-2, reduciendo síntesis de prostaglandinas — incluidas las que mantienen la perfusión de la arteriola aferente renal.",
    vidaMediaHoras: 11, vidaMediaLabel: "~11 h", reduccionA1c: null,
    titr: { l: ["Uso actual"], d: [1] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 2, egfrMin: 0, contra: ["EMBARAZO"] },

  { id: "LITIO", cat: "otros", grp: "Estabilizador del Ánimo", name: "Litio", ini: "N/A", mant: "N/A",
    adv: "Ventana terapéutica estrecha. IECA/ARA-II/Tiazidas reducen su depuración renal — riesgo de litemia tóxica sin cambiar la dosis de litio (Caso 51).",
    mecanismo: "Mecanismo de acción como estabilizador del ánimo no completamente dilucidado; se elimina casi exclusivamente por vía renal (reabsorción proximal ligada a sodio).",
    vidaMediaHoras: 21, vidaMediaLabel: "~18-24 h (más prolongada si hay daño renal)", reduccionA1c: null,
    titr: { l: ["Uso actual"], d: [1] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 1, egfrMin: 0, contra: ["EMBARAZO"] },

  { id: "OLANZ", cat: "otros", grp: "Antipsicótico Alto Riesgo Metabólico", name: "Olanzapina", ini: "N/A", mant: "N/A",
    adv: "Antipsicótico 2ª gen. de mayor riesgo metabólico de la clase (aumento de peso, dislipidemia, resistencia a la insulina) — consenso ADA/APA/AACE/NAASO 2004. Ver Caso 50.",
    mecanismo: "Antagonista de receptores dopaminérgicos D2 y serotoninérgicos 5-HT2A, con afinidad adicional por receptores histaminérgicos H1 (contribuye al aumento de peso).",
    vidaMediaHoras: 30, vidaMediaLabel: "~30 h (rango 21-54 h)", reduccionA1c: null,
    titr: { l: ["Uso actual"], d: [1] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 2, egfrMin: 0, contra: [] },

  { id: "CLOZA", cat: "otros", grp: "Antipsicótico Alto Riesgo Metabólico", name: "Clozapina", ini: "N/A", mant: "N/A",
    adv: "Antipsicótico 2ª gen. de alto riesgo metabólico, reservado típicamente para esquizofrenia resistente a tratamiento — mismo riesgo de ganancia de peso/dislipidemia/resistencia a la insulina. Ver Caso 50.",
    mecanismo: "Antagonista de múltiples receptores (D1-D4, 5-HT2A, H1, muscarínicos, α-adrenérgicos) — perfil de baja afinidad D2 es lo que la distingue de otros antipsicóticos.",
    vidaMediaHoras: 12, vidaMediaLabel: "~12 h (rango 8-16 h)", reduccionA1c: null,
    titr: { l: ["Uso actual"], d: [1] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 2, egfrMin: 0, contra: [] },

  { id: "RITON", cat: "otros", grp: "TARV Potenciado", name: "Ritonavir (potenciador)", ini: "N/A", mant: "N/A",
    adv: "Usado casi siempre en dosis bajas como POTENCIADOR farmacocinético de otro inhibidor de proteasa (ej. Darunavir/r, Atazanavir/r), no como antirretroviral principal. Inhibidor potente de CYP3A4 — ver Caso 54 (Simvastatina contraindicada; Atorvastatina deprioritada).",
    mecanismo: "Inhibidor potente de CYP3A4 (y de la glicoproteína-P) — eleva marcadamente los niveles plasmáticos de fármacos metabolizados por esa vía, incluidas varias estatinas.",
    vidaMediaHoras: 4, vidaMediaLabel: "~3-5 h", reduccionA1c: null,
    titr: { l: ["Uso actual"], d: [1] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 2, egfrMin: 0, contra: [] },

  { id: "COBI", cat: "otros", grp: "TARV Potenciado", name: "Cobicistat (potenciador)", ini: "N/A", mant: "N/A",
    adv: "Potenciador farmacocinético sin actividad antirretroviral propia (a diferencia de ritonavir) — se usa junto a un inhibidor de proteasa o integrasa. Mismo riesgo de interacción CYP3A4 que ritonavir — ver Caso 54.",
    mecanismo: "Inhibidor potente y selectivo de CYP3A4, sin actividad antirretroviral — eleva marcadamente los niveles plasmáticos de fármacos metabolizados por esa vía, incluidas varias estatinas.",
    vidaMediaHoras: 3.5, vidaMediaLabel: "~3-4 h", reduccionA1c: null,
    titr: { l: ["Uso actual"], d: [1] },
    benef: { ic: false, erc: false, ascvd: false, stroke: false, masld: false },
    hipo: "bajo", peso: "neutro", costo: 2, egfrMin: 0, contra: [] },
];
